#!/bin/bash

#all
#bazel test --config=darwin heron/...

#selected
bazel test --config=ubuntu heron/packing/tests/java:RoundRobinPackingTest
bazel test --config=ubuntu heron/packing/tests/java:HomogeneousPackingTest
