#!/bin/bash

#all, with release optimization
CACHE=
if [[ -d /mnt ]]; then CACHE=--output_base=/mnt/bazel_cache; fi
bazel $CACHE build -c opt --config=ubuntu heron/...
bazel $CACHE build -c opt --config=ubuntu scripts/packages:binpkgs  
bazel $CACHE build -c opt --config=ubuntu scripts/packages:tarpkgs


#all, no optimization
#bazel build --config=ubuntu heron/...
#bazel build --config=ubuntu scripts/packages:binpkgs  
#bazel build --config=ubuntu scripts/packages:tarpkgs

#selected
#bazel build heron/packing/src/java:trevorpacking-packing
#bazel build heron/packing/tests/java:HomogeneousPackingTest
