#!/bin/bash

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install git build-essential automake cmake libtool zip \
  libunwind-setjmp0-dev zlib1g-dev unzip pkg-config -y
export CC=/usr/bin/gcc-4.8
export CCX=/usr/bin/g++-4.8
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update -y
sudo apt-get install oracle-java8-installer -y
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
wget -O /tmp/bazel.sh https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel-0.3.1-installer-linux-x86_64.sh
chmod +x /tmp/bazel.sh
/tmp/bazel.sh --user
sudo apt-get install  python-dev python-pip
export PATH="$PATH:$HOME/bin"

